name: Build and deploy PHP app to Azure Web App - game-checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, ctype, fileinfo, pdo, pdo_mysql, tokenizer, xml, dom, curl, gd, zip
          coverage: none

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'backend-laravel/composer.json'

      - name: Run composer install
        if: steps.check_files.outputs.files_exists == 'true'
        working-directory: backend-laravel
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader
          php artisan config:cache
          php artisan route:cache

      - name: Prepare deployment package
        run: |
          cd backend-laravel
          zip -r ../php-app.zip . -x "storage/logs/*" "node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: php-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_21DD0617CC0D42DAA0BA3B707C5A63D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_06A8E081C08F47CD9F77B30DEA3EF954 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_793E5F7AA6004712954E8DC17C157B2B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: game-checker
          package: php-app.zip

      - name: Run Laravel Migrations
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config appsettings set --name game-checker --resource-group rg-game-checker --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
            az webapp ssh -n game-checker -g rg-game-checker --command "php /home/site/wwwroot/artisan migrate --force"
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_793E5F7AA6004712954E8DC17C157B2B }}
          AZURE_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_06A8E081C08F47CD9F77B30DEA3EF954 }}
          AZURE_CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_21DD0617CC0D42DAA0BA3B707C5A63D3 }}
